environment:
  matrix:
    - job_name: Ubuntu Linux build
      appveyor_build_worker_image: Ubuntu2004

    - job_name: MacOS build
      appveyor_build_worker_image: macos-monterey
            
    - job_name: Windows VS 2019 build
      appveyor_build_worker_image: Visual Studio 2019
      
for:
-
  matrix:
    only:
      - job_name: MacOS build
  install:
  - source ~/venv3.10/bin/activate
  - pip install --upgrade pip
  - pip install conan
  - conan profile detect
  
  test_script:
  - cd ..
  - git clone https://github.com/dimi309/portaudio-conan
  - cd portaudio-conan
  - conan export . --version=19.7.0
  - cd ..
  - git clone https://github.com/dimi309/small3d-conan
  - cd small3d-conan
  - conan export . --version=master
  - cd ../gloom
  - conan build . -s compiler.cppstd=gnu17 --build=missing
  
-
  matrix:
    only:
      - job_name: Ubuntu Linux build

  install:
  - sudo apt-get update
  - sudo apt-get -y install libgl-dev libglu1-mesa-dev glslang-tools libasound2-dev libx11-dev libx11-xcb-dev libfontenc-dev libice-dev libsm-dev libxau-dev libxaw7-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxdmcp-dev libxext-dev libxfixes-dev libxft-dev libxi-dev libxinerama-dev libxkbfile-dev libxmu-dev libxmuu-dev libxpm-dev libxrandr-dev libxrender-dev libxres-dev libxss-dev libxt-dev libxtst-dev libxv-dev libxvmc-dev libxxf86vm-dev xtrans-dev libxcb-render0-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev xkb-data libxcb-dri3-dev libxcb-util-dev
  - source ~/venv3.10/bin/activate
  - pip install --upgrade pip
  - pip install conan
  - conan profile detect

  test_script:
  - cd ..
  - git clone https://github.com/dimi309/portaudio-conan
  - cd portaudio-conan
  - conan export . --version=19.7.0
  - cd ..
  - git clone https://github.com/dimi309/small3d-conan
  - cd small3d-conan
  - conan export . --version=master
  - cd ../gloom
  - conan build . --build=missing -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True
  
-
  matrix:
    only:
      - job_name: Windows VS 2019 build

  install:
  - set PATH=C:\Python38-x64;C:\Python38-x64\scripts;%PATH%
  - python -m pip install --upgrade pip
  - pip install conan
  - conan profile detect

  test_script:
  - cd ..
  - git clone https://github.com/dimi309/portaudio-conan
  - cd portaudio-conan
  - conan export . --version=19.7.0
  - cd ..
  - git clone https://github.com/dimi309/small3d-conan
  - cd small3d-conan
  - conan export . --version=master
  - cd ../gloom
  - conan build . -s compiler.cppstd=17 --build=missing

build: off
